name: school_time
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


# `flutter pub upgrade --major-versions`` to upgrade all the dependencies.
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  lint: ^1.8.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
    # - images/a_dot_burr.jpeg